# SO 4578-8729

include ../../etc/soq-head.mk

PROG1 = so-4578-8729-mcve
PROG2 = so-4578-8729-mk5
PROG3 = so-4578-8729-mk6
PROG4 = so-4578-8729-original
PROG5 = so-4578-8729-owd
PROG6 = so-4578-8729-owd2
PROG7 = so-4578-8729

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6} ${PROG7}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
