# SO 5011-0992

include ../../etc/soq-head.mk

PROG1 = neof11
PROG2 = neof19
PROG3 = neof67
PROG4 = neof97

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
