# SO 4859-9507

include ../../etc/soq-head.mk

PROG1 = ext_program
PROG2 = phantomjs
PROG3 = pipe11
PROG4 = pipe19
PROG5 = pipe31
PROG6 = pipe37
PROG7 = pipe89

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6} ${PROG7}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
