# sortfile

include ../../etc/soq-head.mk

PROG1 = sortlines1
PROG2 = sortlines2
PROG3 = sortlines3
PROG4 = sortwords1
PROG5 = sortwords2

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
