# SO 1880-1547

include ../../etc/soq-head.mk

PROG1 = rle
PROG2 = zigzag1
PROG3 = zigzag2
PROG4 = zigzag3
PROG5 = zigzag4
PROG6 = zigzag5
PROG7 = zigzag6
PROG8 = zigzag7
PROG9 = zigzag8

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6} ${PROG7} ${PROG8} ${PROG9}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
