# SO 7918-2426

include ../../etc/soq-head.mk

CC = clang -Wno-nullability-completeness

PROG1 = spiral29
PROG2 = spiral41
PROG3 = spiral79
PROG4 = spiral83
PROG5 = spiral89

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
