# To suppress JL-specific options:
# LDLIBS= LDFLAGS= IFLAGS=

include ../etc/soq-head.mk

BASEDIR = ..

PROG1 = palindrome29
PROG2 = palindrome73
PROG3 = palindrome83

PROGRAMS = ${PROG1} ${PROG2} ${PROG3}

all: ${PROGRAMS}

include ../etc/soq-tail.mk
