# SO 5332-1864

include ../../etc/soq-head.mk

IFLAG2  = -I${HOME}/inc
LDFLAG2 = -L${HOME}/lib/64
LDLIB2  = -ljl

PROG1 = ads13
PROG2 = ads29
PROG3 = ads41
PROG4 = ads47

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
