# SO 37106523

include ../../etc/soq-head.mk

PROG1 = trie-31

OUTFILES = data

PROGRAMS = ${PROG1}

all: ${PROGRAMS}

test:	${PROGRAMS}
	${CP} ${PROG1}.c ${OUTFILES}; ${PROG1}

include ../../etc/soq-tail.mk
