# Project 3 - CS221 Fall 2018
# Your program must compile with 'make'
# You must not change this file.

CC = gcc
CFLAGS = -std=c99 -O0 -Wall -Werror -g -pedantic
CFLAGS = -std=c99 -O3 -Wall -Werror -g -pedantic -Wmissing-prototypes -Wstrict-prototypes -Wextra

PROG1 = climate
PROG2 = climate-v2
PROG3 = climate-v3
PROG4 = climate-v4
PROGS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGS}

clean:
	rm -f ${PROGS}
	rm -rf *.dSYM

