# SO 4987-1989
# Generic Swap Algorithms

include ../../etc/soq-head.mk

PROG1 = swap89
PROG2 = dsw47
PROG3 = gnsw29

PROGRAMS = ${PROG1} ${PROG2} ${PROG3}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
