# @(#)SO 3666-8295 - Postfix to Infix Conversion

include ../../etc/soq-head.mk

PROGRAM1 = postfix-infix
PROGRAM2 = so.36668295

PROGRAMS = ${PROGRAM1} ${PROGRAM2}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
