# SO 4544-8234

include ../../etc/soq-head.mk

PROG1 = mt11
PROG2 = gen.sinusoid
PROG3 = mon.grouping
PROG4 = mt89
PROG5 = mt29
PROG6 = gen.data

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
