# SO 45448234

include ../../etc/soq-head.mk

PROG1 = mt11
PROG2 = gen.sinusoid
PROG3 = mon.grouping
PROG4 = mt89

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
