# SO 7074-5657

include ../../etc/soq-head.mk

PROG1 = sig11
PROG2 = sig13
PROG3 = sig17
PROG4 = sig19
PROG5 = sig23
PROG6 = sig29
PROG7 = sig71
PROG8 = sig73

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6} ${PROG7} ${PROG8}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
