# To suppress JL-specific options:
# LDLIBS= LDFLAGS= IFLAGS=

include ../etc/soq-head.mk

BASEDIR = ..

PROG1 = Control
PROG2 = PipeW1
PROG3 = PipeW2
PROG4 = PipeR

PROGS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGS}

include ../etc/soq-tail.mk
