# SO 46859611

include ../../etc/soq-head.mk

PROG1 = ctac13
PROG2 = ctac41
PROG3 = ctac83
PROG4 = domains13
PROG5 = rankin29
PROG6 = rankin37
PROG7 = domains73
PROG8 = domains83
PROG9 = domains97

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6} ${PROG7} ${PROG8} ${PROG9}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
