# To suppress JL-specific options:
# LDLIBS= LDFLAGS= IFLAGS=

include ../../etc/soq-head.mk

# This code only compiles on Linux.
# The primary platform used here is macOS.
# Compilation is disabled by default.
#PROGRAMS = clone41

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
