# SO 6511-7221

include ../../etc/soq-head.mk

PROG0 = matmul97	# Original
PROG1 = matmul47	# 1x1
PROG2 = matmul89	# 2x2
PROG3 = matmul67	# 4x4
PROG4 = matmul73	# 8x8
PROG5 = matmul23	# NxN

PROGRAMS = ${PROG0} ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
