# SO 7063-3743

include ../../etc/soq-head.mk

PROG1 = md19
PROG2 = md41
PROG3 = md43
PROG4 = md17-generator

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
