# SO 5630-7028

include ../../etc/soq-head.mk

PROG1 = overlap31
PROG2 = overlap47
PROG3 = overlap61
PROG4 = overlap73

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
