# Questions about multi-dimensional arrays in C

include ../../etc/soq-head.mk

PROG01 = 2da
PROG02 = 3dalloc1
PROG03 = 3dalloc2
PROG04 = 3dalloc3
PROG05 = 3dalloc4
# PROG06 =
PROG07 = matmake3d
PROG08 = matmul89
PROG09 = matmul99
PROG10 = mda
PROG11 = vlamat
PROG12 = vlastruct

PROGRAMS = \
	${PROG01} \
	${PROG02} \
	${PROG03} \
	${PROG04} \
	${PROG05} \
	${PROG07} \
	${PROG08} \
	${PROG09} \
	${PROG10} \
	${PROG11} \
	${PROG12} \

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
