# SO 13827096

include ../../etc/soq-head.mk

PROG1 = incunabulum
PROG2 = modern-incunabulum

PROGRAMS = ${PROG1} ${PROG2}

CFLAGS = -m32
LDFLAGS =
LDLIBS =

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
