# SO 30794962
# SO 35147784
# SO 37075084 - now deleted

include ../../etc/soq-head.mk

PROGRAMS = \
	binsearch-speed \
	bs-files \
	bsmax \
	bsmin \
	modbinsearch \
	shiftbinsearch \

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
