# SO 30794962
# SO 35147784
# SO 37075084 - now deleted

include ../../etc/soq-head.mk

PROGRAMS = \
	binsearch-speed \
	bs-files \
	bscheck \
	bsmax \
	bsmin \
	bsrange \
	modbinsearch \
	shiftbinsearch \

all: ${PROGRAMS}

bscheck: bscheck.c bsearch.c

include ../../etc/soq-tail.mk
