# SO 3901-5527

include ../../etc/soq-head.mk

PROG1 = readdir
PROG2 = rename
PROG3 = make.files.sh

PROGRAMS = ${PROG1} ${PROG2} ${PROG3}

OUTFILES = moderately-long-file-name.* zzz-let-sleeping-file-renames-lie-unperturbed

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
