# SO 38494701

include ../../etc/soq-head.mk

PROG1 = gen-samples1
PROG2 = gen-samples2
PROG3 = join-samples
PROG4 = three-file-solution

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
