# SO 5256-3870

include ../../etc/soq-head.mk

PROG1 = array-range-17
PROG2 = array-range-19
PROG3 = array-range-23
PROG4 = array-range-29

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
