# Makefile for 5 of 6 programs for a Programming Challenge on Medium
# (Better Programming)

include ../../etc/soq-head.mk

PROG1 = dp97
PROG2 = kaprekars-constant-17
PROG3 = lpp13
PROG4 = pmf23
PROG5 = revpairs71

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
