# SO 0333-0048

include ../../etc/soq-head.mk

PROG1 = pthread-1
PROG2 = pthread-2
PROG3 = pthread-3

LDLIB2 = -lpthread

PROGRAMS = ${PROG1} ${PROG2} ${PROG3}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
