# SO 48013629

include ../../etc/soq-head.mk

IFLAG2  = -I${HOME}/inc
LDFLAG2 = -L${HOME}/lib/64
LDLIB2  = -ljl

# JL
PROG1 = punc37
PROG2 = punc41
PROG3 = punc47

# JG and NS
PROG4 = punc73
PROG5 = punc89
PROG5 = punc97

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
