# SO 1843-7779

include ../../etc/soq-head.mk

PROG1 = sigalrm
PROG2 = sigchld
PROG3 = signals
PROG4 = sigsync
PROG5 = sigexit73

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
