# SO 18437779

include ../../etc/soq-head.mk

PROG1 = sigalrm
PROG2 = sigchld
PROG3 = signals
PROG4 = sigsync

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
