# SO 7916-7448

include ../../etc/soq-head.mk

PROG1 = sine17
PROG2 = sine47
PROG3 = sine59
PROG4 = sine97

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
