# To suppress JL-specific options:
# LDLIBS= LDFLAGS= IFLAGS=

include ../etc/soq-head.mk

BASEDIR = ..

PROG1 = argc37
PROG2 = argv89

SCRIPTS = maxargs

PROGRAMS = ${PROG1} ${PROG2}

all: ${PROGRAMS} ${SCRIPTS}

OUTFILES = ${SCRIPTS}

include ../etc/soq-tail.mk
