# SO 41032361

include ../../etc/soq-head.mk

PROG1 = ng37
PROG2 = ng41
PROG3 = ng41a
PROG4 = ng43
PROG5 = ng43a
PROG6 = ng47
PROG7 = ng47a
PROG8 = ng53
PROG9 = ng59
PROG10 = ng61

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6} ${PROG7} ${PROG8} ${PROG9} ${PROG10}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
