# SO 41032361

include ../../etc/soq-head.mk

PROG01 = ng37
PROG02 = ng41
PROG03 = ng41a
PROG04 = ng43
PROG05 = ng43a
PROG06 = ng47
PROG07 = ng47a
PROG08 = ng53
PROG09 = ng59
PROG10 = ng61
PROG11 = udn
PROG12 = logcntr

PROGRAMS = \
	${PROG01} \
	${PROG02} \
	${PROG03} \
	${PROG04} \
	${PROG05} \
	${PROG06} \
	${PROG07} \
	${PROG08} \
	${PROG09} \
	${PROG10} \
	${PROG11} \
	${PROG12} \

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
