# To suppress JL-specific options:
# LDLIBS= LDFLAGS= IFLAGS=

include ../../etc/soq-head.mk

PROG01 = mm11
PROG02 = mm47
PROG03 = mm61
PROG04 = mm89
PROG05 = mm97

PROGRAMS = ${PROG01} ${PROG02} ${PROG03} ${PROG04} ${PROG05}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
