# To suppress JL-specific options:
# LDLIBS= LDFLAGS= IFLAGS=

include ../etc/soq-head.mk

PROG1 = sc19
PROG2 = sc61

PROGS = ${PROG1} ${PROG2}

BASEDIR = ..

all: ${PROGS}

clean:
	${RM_FR} ${DEBRIS} *.dSYM

realclean:
