# SO 5145-7357

include ../../etc/soq-head.mk

PROG1 = ch11
PROG2 = ch43
PROG3 = fp17
PROG4 = fp53
PROG5 = wv47
PROG6 = wv53

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
