# SO 4746-4803

include ../../etc/soq-head.mk

PROG1 = mtx17
PROG2 = mtx29
PROG3 = mtx43
PROG4 = mtx59
PROG5 = mtx61
PROG6 = mtx61p
PROG7 = mtx83
PROG8 = mtx83p

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6} ${PROG7} ${PROG8}

OUTFILES = *.out

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
