# SO 7406-2431

include ../../etc/soq-head.mk

PROG1 = dirlist17
PROG2 = dirlist43
PROG3 = dirlist67
PROG4 = dirlist73

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

TFLAGS = -DUNIX

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
