# SO 7483-2964

include ../../etc/soq-head.mk

# Original program - using scanf_s() and printf_s()
#PROG1 = matmul13

PROG2 = matmul43
PROG3 = matmul53
PROG4 = matmul89

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
