# SO 5651-9149

include ../../etc/soq-head.mk

PROG1 = conn11
PROG2 = conn13
PROG3 = conn17
PROG4 = conn29

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
