# Makefile for miscellany directory

include ../../etc/soq-head.mk

PROG1 = #incunabulum
PROG2 = #modern-incunabulum
PROG3 = stld
PROG4 = rangesquash1
PROG5 = rangesquash2
PROG6 = rangesquash3
PROG7 = rangesquash4
PROG8 = lcm20

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6} ${PROG7} ${PROG8}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
