# Makefile for miscellany directory

include ../../etc/soq-head.mk

PROG01 = #incunabulum-ancient
PROG02 = #incunabulum-modern
PROG03 = stld
PROG04 = rangesquash1
PROG05 = rangesquash2
PROG06 = rangesquash3
PROG07 = rangesquash4
PROG08 = lcm20
PROG09 = test-rename
PROG10 = check-rename
PROG11 = quine-c
PROG12 = quine-py
PROG13 = #dec_to_hex
PROG14 = map
PROG15 = uint128
PROG16 = rev
PROG17 = revlist
PROG18 = select
PROG19 = factorial
PROG20 = random59
PROG21 = suit9

PROGRAMS = \
	${PROG01} \
	${PROG02} \
	${PROG03} \
	${PROG04} \
	${PROG05} \
	${PROG06} \
	${PROG07} \
	${PROG08} \
	${PROG09} \
	${PROG10} \
	${PROG11} \
	${PROG12} \
	${PROG13} \
	${PROG14} \
	${PROG15} \
	${PROG16} \
	${PROG17} \
	${PROG18} \
	${PROG19} \
	${PROG20} \
	${PROG21} \

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
