# Makefile for miscellany directory

include ../../etc/soq-head.mk

PROG01 = #incunabulum
PROG02 = #modern-incunabulum
PROG03 = stld
PROG04 = rangesquash1
PROG05 = rangesquash2
PROG06 = rangesquash3
PROG07 = rangesquash4
PROG08 = lcm20
PROG09 = test-rename
PROG10 = check-rename
PROG11 = quine-c
PROG12 = quine-py

PROGRAMS = \
	${PROG01} \
	${PROG02} \
	${PROG03} \
	${PROG04} \
	${PROG05} \
	${PROG06} \
	${PROG07} \
	${PROG08} \
	${PROG09} \
	${PROG10} \
	${PROG11} \
	${PROG12} \

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
