# SO 4203-5818

include ../../etc/soq-head.mk

PROG1 = st13
PROG2 = st17
PROG3 = st19
PROG4 = test.st19

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
