# SO 4203-5818
#
# Various rather specialized sorting algorithms
# st13, st17, st19 sort three variables.
# s6v23, s6v59 sort six variables
# tp13, tp17, tp43, tp47 are from my answer to SO 4203-5818

include ../../etc/soq-head.mk

PROG01 = st13
PROG02 = st17
PROG03 = st19
PROG04 = test.st19
PROG05 = s6v23
PROG06 = s6v59
PROG07 = tp13
PROG08 = tp17
PROG09 = tp43
PROG10 = tp47

PROGRAMS =  \
	${PROG01} \
	${PROG02} \
	${PROG03} \
	${PROG04} \
	${PROG05} \
	${PROG06} \
	${PROG07} \
	${PROG08} \
	${PROG09} \
	${PROG10} \

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
