# SO 4203-5818
#
# Various rather specialized sorting algorithms
# st13, st17, st19 sort three variables.
# s6v23, s6v59 sort six variables

include ../../etc/soq-head.mk

PROG1 = st13
PROG2 = st17
PROG3 = st19
PROG4 = test.st19
PROG5 = s6v23
PROG6 = s6v59

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
