# SO 4747-6170
#
# Unusually, leave all scripts with suffixes in place.
# The macros are named 'scripts' instead of 'programs' to
# prevent devastation when 'make clean' is run.

include ../../etc/soq-head.mk

SCRIPT01 = awkscript-256.sh
SCRIPT02 = awkscript.sh
SCRIPT03 = chepner-1.sh
SCRIPT04 = chepner-2.sh
SCRIPT05 = data.generator.sh
SCRIPT06 = data.summarizer.sh
SCRIPT07 = jlscript.pl
SCRIPT08 = jlscript.sh
SCRIPT09 = map-names.sh
SCRIPT10 = opscript.sh
SCRIPT11 = pyscript.py
SCRIPT12 = tab-normal.sh
SCRIPT13 = fmt-tabulate.awk
SCRIPT14 = tabulate.sh
SCRIPT15 = test-script.sh

SCRIPTS = \
	${SCRIPT01} \
	${SCRIPT02} \
	${SCRIPT03} \
	${SCRIPT04} \
	${SCRIPT05} \
	${SCRIPT06} \
	${SCRIPT07} \
	${SCRIPT08} \
	${SCRIPT09} \
	${SCRIPT10} \
	${SCRIPT11} \
	${SCRIPT12} \
	${SCRIPT13} \
	${SCRIPT14} \
	${SCRIPT15} \

all: ${SCRIPTS}

include ../../etc/soq-tail.mk
