# SO 7121-4579

include ../../etc/soq-head.mk

PROG1 = xmacro17
PROG2 = xmacro19
PROG3 = xmacro71
PROG4 = xmacro97

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
