# SO 5308-6674

include ../../etc/soq-head.mk

PROG1 = npa67
PROG2 = prim29
PROG3 = rhom59
PROG4 = bsmnmx
PROG5 = npt23

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
