# SO 4295-4541

include ../../etc/soq-head.mk

PROG1 = bsort1
PROG2 = bsort2
PROG3 = bsort3
PROG4 = bsort4
PROG5 = bsort5

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
