# SO 46736148

include ../../etc/soq-head.mk

PROG1 = so-4673-6148A
PROG2 = so-4673-6148B
PROG3 = so-4673-6148C

PROGRAMS = ${PROG1} ${PROG2} ${PROG3}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
