# SO 4673-6148

include ../../etc/soq-head.mk

PROG1 = so-4673-6148A
PROG2 = so-4673-6148B
PROG3 = so-4673-6148C
PROG4 = so-4673-6148D

PROG5 = analysis2
PROG6 = raw-analysis2

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
