# SO 4929-0953

include ../../etc/soq-head.mk

PROG1 = sort3-17
PROG2 = sort3-29
PROG3 = sort3-53
PROG4 = sort3-79
PROG5 = sortnet3-89

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
