# SO 5208-4867

include ../../etc/soq-head.mk

PROG1 = wexp19
PROG2 = wexp79
PROG3 = so-5246-1162-b
PROG4 = esc11

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
