include ../etc/soq-head.mk

TFLAGS = -DTEST
LIBDIR = ../lib
HDRDIR = ../inc

PROGRAMS = \
	arrstrings \
	bash-assoc-arrays \
	discover \
	gcc-filter \
	genshuffle \
	kwargs \
	run-shm-master \
	select \
	shm-master \
	sigsync \
	sortfile1 \
	sortfile2 \

all: ${PROGRAMS}

include ../etc/soq-tail.mk
