# SO 4633-6404

include ../../etc/soq-head.mk

PROG1 = script1
PROG2 = script2
PROG3 = script3
PROG4 = script4

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

OUTFILES = file.1 file.2 file.3

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
