include ../etc/soq-head.mk

TFLAGS = -DTEST
LIBDIR = ../lib
HDRDIR = ../inc

PROGRAMS = \
	chk-utf8-test \
	chk-wchar-test \
	utf8-test \
	wchar-test \
	x37 \

all: ${PROGRAMS}

include ../etc/soq-tail.mk
