# SO 4840-7614

include ../../etc/soq-head.mk

PROG1 = perlin23
# RMK doesn't support Java by default.
#PROG2 = ImprovedNoise.class
#PROG2 = ImprovedNoise.java
LDLIB2 = -lm

OUTFILES = ImprovedNoise.class

PROGRAMS = ${PROG1}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
