# SO 1974-7644

include ../../etc/soq-head.mk

IFLAG2  = -I${HOME}/inc
LDFLAG2 = -L${HOME}/lib/64
LDLIB2  = -ljl

PROG1 = run-processes
PROG2 = numproc23

PROGRAMS = ${PROG1} ${PROG2}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
