# To suppress JL-specific options:
# LDLIBS= LDFLAGS= IFLAGS=

include ../etc/soq-head.mk

BASEDIR = ..

IFLAG2  = -I${HOME}/inc
LDFLAG2 = -L${HOME}/lib/64
LDLIB2  = -ljl

PROGRAM = chunker79

all: ${PROGRAM}

include ../etc/soq-tail.mk
