# SO 5173-7998

include ../../etc/soq-head.mk

#PROG1 = ll13
PROG2 = ll43
PROG3 = ll61
PROG4 = rsll17
PROG5 = rsll67
PROG6 = rsll73

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
