# SO 3994-9116
# SO 4997-3644

include ../../etc/soq-head.mk

PROG1 = trie89
PROG2 = trie-search13
PROG3 = trie-split59
PROG4 = trie-split67

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
