# SO 44792794.20170709.203100.tar.gz

include ../../etc/soq-head.mk

PROG1 = add-readme
PROG2 = mkmk
PROG3 = updmkfile

PROGRAMS = ${PROG1} ${PROG2} ${PROG3}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
