# SO 4555-1869

include ../../etc/soq-head.mk

PROG1 = pth11
PROG2 = pth13
PROG3 = pth17
PROG4 = pth19

LDLIB2 = -lpthread

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
