# SO 0429-4928

include ../../etc/soq-head.mk

PROG1    = send
PROG2    = recv
PROGRAMS = ${PROG1} ${PROG2}

all:	${PROGRAMS}

${PROG1}: ${LIBPATH}
${PROG2}: ${LIBPATH}

include ../../etc/soq-tail.mk
