#!/bin/bash
#
# Run eratosthenes-5 and show the count and sum
# Validate with 'test-0'
#
# Originally needed to eliminate the list of prime numbers, but the
# program only generates them now if invoked with the -v option (hence
# you might run: eratosthenes-5 "-v 1000" for example).

count=${1:-1000}

: "${MAKE:=make}"

if ${MAKE} -q eratosthenes-5 ||
   ${MAKE}    eratosthenes-5
then
    timecmd -m -- eratosthenes-5 $count
    timecmd -m -- test-0 $count
fi
