#!/bin/bash
#
# Generate the count and sum of primes up to a given value.
#
# Uses quasi-independent program 'primes' to generate a list of prime
# numbers, and then 'wc' and 'total' to count and sum the values.
# The output is similar to what the eratosthenes-N programs generate.

count=${1:-1000}

tmp="${TMPDIR:-/tmp}/t6.$$"
trap "rm -f $tmp.?; exit 1" 0 1 2 3 13 15
primes $count | tpipe -s "wc -l >$tmp.1" "total > $tmp.2"
printf "Sum   of primes to $count = %d\n" $(<$tmp.2)
printf "Count of primes to $count = %d\n" $(<$tmp.1)
rm -f $tmp.?
trap 0
