#!/bin/bash

count=${1:-1000}

if rmk -q eratosthenes-6 eratosthenes-5 ||
   rmk    eratosthenes-6 eratosthenes-5
then
    #valgrind --suppressions=../suppressions eratosthenes-6 $count
    eratosthenes-6 ${E6_DEBUG} $count
    eratosthenes-5 $count
    test-0 $count
fi
