#!/bin/bash

count=${1:-1000}

: "${MAKE:=make}"

if ${MAKE} -q eratosthenes-6 eratosthenes-5 ||
   ${MAKE}    eratosthenes-6 eratosthenes-5
then
    #valgrind --suppressions=../suppressions eratosthenes-6 $count
    timecmd -m -- eratosthenes-6 ${E6_DEBUG} $count
    timecmd -m -- eratosthenes-5 $count
    timecmd -m -- test-0 $count
fi
