# SO 5405-4423

include ../../etc/soq-head.mk

PROG1 = strncat19
PROG2 = strncat29
PROG3 = strncat37
PROG4 = strncat97

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
