# SO 11027679

include ../../etc/soq-head.mk

PROG0 = qs47

PROG1 = qs-01-int
PROG2 = qs-02-str
PROG3 = qs-03-2da
PROG4 = qs-04-asp
PROG5 = qs-05-date
PROG6 = qs-06-bad

PROGRAMS = ${PROG0} ${PROG1} ${PROG2} ${PROG3} ${PROG4} ${PROG5} ${PROG6}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
