# Quicksort documentation

include ../../etc/soq-head.mk

PROG0 = qs47

PROG01 = qs-01-int
PROG02 = qs-02-str
PROG03 = qs-03-2da
PROG04 = qs-04-asp
PROG05 = qs-05-date
PROG06 = qs-06-bad
PROG07 = qs-07-int
PROG08 = ls73
PROG09 = ls79
PROG10 = qs79
PROG11 = sr19
PROG12 = oddascevendesc

PROGRAMS = \
	${PROG00} \
	${PROG01} \
	${PROG02} \
	${PROG03} \
	${PROG04} \
	${PROG05} \
	${PROG06} \
	${PROG07} \
	${PROG08} \
	${PROG09} \
	${PROG10} \
	${PROG11} \
	${PROG12} \

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
