# SO 4418-0272

include ../../etc/soq-head.mk

PROG1 = log59
PROG2 = log61
PROG3 = log67
PROG4 = log73

PROGRAMS = ${PROG1} ${PROG2} ${PROG3} ${PROG4}

all: ${PROGRAMS}

include ../../etc/soq-tail.mk
