# To suppress JL-specific options:
# LDLIBS= LDFLAGS= IFLAGS=

include ../../etc/soq-head.mk

IFLAG2 = -I${HOME}/inc
LDLIB2 = -ljl
LDFLAG2 = -L${HOME}/lib/64

PROGRAMS = cpd-client cpd-server client-20170706 server-20170706

all: ${PROGRAMS}
